
name: build
on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
  
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: build
      run: |
        docker build . --file aks-dockerfile --tag spark --label "runnumber=${GITHUB_RUN_ID}"
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login docker.io -u chenkewen2 --password-stdin
    - name: push
      run: |
          IMAGE_NAME=docker.io/chenkewen2/spark
          docker tag spark $IMAGE_NAME:${{ github.sha }}
          docker push $IMAGE_NAME:${{ github.sha }}
          
 
  
      
      







          
